name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # Generates every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: VISHWA-SANTHI
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
 
      - name: Push to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
